#define ID_APPICON        201
#define ID_BTN_CREATEDB   202
#define ID_BTN_DECRYPT    203
#define ID_SAVE           204
#define ID_EXIT           205
#define ID_SETTINGS       206
#define ID_INFO           207
#define ID_WEBSITE        208
#define ID_MODALBOX       209
#define ID_ACCEL          210
#define ID_DATABASE       211
#define ID_LOCK           212
#define ID_FOCUS_SWITCH   213
#define ID_FOCUS_FILTER   214
#define ID_FOCUS_EDITOR   215
#define ID_TIMEOUT_EDITOR 216
